#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/var/log/couchpotato

# install app now with apikey
[[ ! -d "/app/couchpotato/.git" ]] && \
	git clone https://github.com/abuhamsa/GoodOldCouchPotato.git /app/couchpotato

# permissions
chown -R abc:abc \
	/app

chmod 777 \
	/var/log/couchpotato
