#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/var/log/couchpotato

# install app
[[ ! -d "/app/couchpotato/.git" ]] && \
	git clone https://github.com/CouchPotato/CouchPotatoServer.git && \
  	git checkout tags/build/2.6.3 -b old_version

# permissions
chown -R abc:abc \
	/app

chmod 777 \
	/var/log/couchpotato
